### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by yusoy** [iionly/izap_videos#3]
Sorry, I'm not familiar with this.
I would simply like to know how I can pass you the translation that I have done to the Spanish language of your plugin.
Regards.
PS: I have added it here bought in zip
[es.zip](https://github.com/iionly/izap_videos/files/5125016/es.zip)

**Comment by iionly** [comment]
Thanks. I'll add the language file to the repository and then it will also be included in the next release. I don't know though, when the next release will happen because I would like to wait at least a while after the recent release for Elgg 3 if any bugs show up.

**Comment by yusoy** [comment]
Well, as you see.
I only provide the translation.
I had to do it for the elgg installation that I did.
Thanks for the plugin

**Comment by iionly** [comment]
Your Spanish language file is included in the 3.3.2 release.
