### ISSUE TITLE
Youtube src

### ISSUE THREAD

**Issue by danhype** [iionly/izap_videos#5]
Hello,

Would it be possible to replace in the file classes/IzapGetFeed.php, line 77 :

'https://www.youtube.com/embed/'

by

'https://www.youtube-nocookie.com/embed/'

for a little more respect for users' privacy ?

Dan

**Comment by iionly** [comment]
I had never known about the nocookie url before. As it's an official url I would think it would be okay to offer it as an option. I think the best way would be to add it as an option and to add a conversion (in both directions) for existing videos. I'll keep it in mind and I would think the next release will contain this feature.

**Comment by danhype** [comment]
Hello,

What would also be great to have in option is the possibility to integrate peertube and individious videos with an option field to put the url of an instance.

Peertube: https://github.com/Chocobozzz/PeerTube
individious: https://github.com/iv-org/invidious

Dan

**Comment by iionly** [comment]
PeerTube is working differently than Youtube. It's a P2P network for videos where you should not just embed videos hosted on other sites but also host videos for others participating in PeerTube. That's not something I want to add to iZAP Videos. individious seems to be an alternative frontend site only. Maybe that works all fine. But I'm not interested in investing time into that.

**Comment by iionly** [comment]
Sorry. But I've decided to not make any changes or at more options for the foreseeable future. I've just too much to maintain already as it is.
